# Generated by Django 3.2.12 on 2022-03-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20220321_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_log_set', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
