# Generated by Django 3.2.12 on 2022-03-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20220321_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
