# Generated by Django 3.2.12 on 2022-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='work_time',
            field=models.DurationField(null=True),
        ),
    ]
