version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres1
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres1
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1
    links:
      - db:db
      - redis:redis
  redis:
    ports:
      - "6379:6379"
    image: "redis:alpine"
    expose:
      - "6379"
  pghero:
    image: ankane/pghero
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgres://postgres1:postgres1@db:5432/postgres1
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
