# Generated by Django 3.2.12 on 2022-03-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='duration',
        ),
    ]
