# Generated by Django 3.2.12 on 2022-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_log_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='stop',
        ),
        migrations.AddField(
            model_name='log',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
